### ISSUE TITLE
Error function not defined for alt-tutorial

### ISSUE THREAD

**Issue by sarathjoseph** [goatslacker/alt-tutorial#12]
LocationStore.hasError is not defined for the alt-tutorial with cities example and hence throws an error

**Comment by goatslacker** [comment]
Ah yes. I'll put up a fix for this later today

**Comment by timqian** [comment]
Has it been repaired? I encounter this error too..

**Comment by goatslacker** [comment]
Done. Thanks for reporting!

**Comment by goatslacker** [comment]
d631294a62420025a4471c2ab3686d2981a8a023
