### ISSUE TITLE
Code here doesn't match the tutorial at all

### ISSUE THREAD

**Issue by octref** [goatslacker/alt-tutorial#18]
By following [getting started guide](http://alt.js.org/guide/) I end up with code completely different from this repo.

A getting started guide which doesn't wrap up with a runnable app and [points](http://alt.js.org/guide/wait-for/) to a repo with different code isn't the best way to document your project, I guess?

**Comment by gajus** [comment]
This code covers everything thats mentioned in the getting started guide, but includes extra info. I don't see that as an issue.

**Comment by benjaminmbrown** [comment]
Agreed -  a working update would be helpful.

**Comment by wwsun** [comment]
no data and fetcher

**Comment by Phifo** [comment]
Agreed, and I don't know if the repo or the documentation is out of date.

**Comment by sthzg** [comment]
Also agreed. At least in terms of the Store the getting started guide seems more up-to-date (`this.dispatch()` is no longer available in the store, also I think it's `registerAsync()` rather than `exportAsync()`).

**Comment by avdeveloper** [comment]
@goatslacker which is more up to date (accurate), the getting started guide or this repo's code?

**Comment by rajasekaranmcait** [comment]
i think this project need to update and clear some issues for proper execution..because this project only directly linked in main reactjs website..

**Comment by octref** [comment]
Guess this project is abandoned. I don't care anymore anyway...
