### ISSUE TITLE
Update alt tutorial to use AltContainer?

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt-tutorial#4]

**Comment by timtyrrell** [comment]
I would be very interested in seeing this on a branch or another repo

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt-tutorial/commit/63cfedd66e9f589131c7ac1593d7049ebf0321c6

**Comment by goatslacker** [comment]
I'll update the getting started guide on alt.js.org to include these changes soon!
