### ISSUE TITLE
Missing utils directory

### ISSUE THREAD

**Issue by TeckniX** [goatslacker/alt-tutorial#6]
During build `browserify -t [reactify --es6] src/App.jsx > build/app.js` , I got the following error:

`Error: Cannot find module '../utils/LocationsFetcher' from './alt-tutorial/src/actions'`

Did you forget to push something?

**Comment by goatslacker** [comment]
Oh no, I forgot to remove the require call from src/actions.

**Comment by goatslacker** [comment]
This line needs to be RM'd https://github.com/goatslacker/alt-tutorial/blob/master/src/actions/LocationActions.js#L2

**Comment by TeckniX** [comment]
:+1:  Works much better that way. Thanks for the quick reply!

**Comment by goatslacker** [comment]
Closing it when I remove the line today.

**Comment by TeckniX** [comment]
May need to update the tutorial then too :P 
http://alt.js.org/guide/async/

**Comment by goatslacker** [comment]
411bf14

**Comment by goatslacker** [comment]
Yup I'll be adding new sections to the tutorial.

**Comment by TeckniX** [comment]
:+1:
